---
title: "Result"
author: "Yicheng Shen"
date: "2023-03-12"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = T, warning = F)
library(metafor)
library(tidyverse)
library(kableExtra)
ggplot2::theme_set(ggplot2::theme_bw())
knitr::opts_chunk$set(out.width = "100%", fig.align = 'center')
```


```{r, fig.height=6, fig.width=10, out.width = "80%"}
load("sim_result_1000.RData")
df = sim_result_1000

a <- df %>% filter(pi_a == 0.1, k_ac == 1) %>% 
  ggplot(aes(x = k_ab, y = power, color = factor(OR_bc))) + geom_line(size = 1.5) + facet_wrap(~tau) + 
  labs(title = "pi_a = 0.1, k_ac = 1", color = "True OR_bc") + theme_bw()

b <- df %>% filter(pi_a == 0.3, k_ac == 1) %>% 
  ggplot(aes(x = k_ab, y = power, color = factor(OR_bc))) + geom_line(size = 1.5) + facet_wrap(~tau) + 
  labs(title = "pi_a = 0.3, k_ac = 1", color = "True OR_bc") + theme_bw()


c <- df %>% filter(pi_a == 0.1, k_ac == 5) %>% 
  ggplot(aes(x = k_ab, y = power, color = factor(OR_bc))) + geom_line(size = 1.5) + facet_wrap(~tau) + 
  labs(title = "pi_a = 0.1, k_ac = 5", color = "True OR_bc") + theme_bw()

d <- df %>% filter(pi_a == 0.3, k_ac == 5) %>% 
  ggplot(aes(x = k_ab, y = power, color = factor(OR_bc))) + geom_line(size = 1.5) + facet_wrap(~tau) + 
  labs(title = "pi_a = 0.3, k_ac = 5", color = "True OR_bc") + theme_bw()


gridExtra::grid.arrange(a,b,c,d)
```


```{r, fig.height=6, fig.width=10, out.width = "80%"}
load("sim_result_1000_1lower.RData")
df = sim_result_1000_1lower

a <- df %>% filter(pi_a == 0.1, k_ac == 1) %>% 
  ggplot(aes(x = k_ab, y = power, color = factor(OR_bc))) + geom_line(size = 1.5) + facet_wrap(~tau) + 
  labs(title = "pi_a = 0.1, k_ac = 1", color = "True OR_bc") + theme_bw()

b <- df %>% filter(pi_a == 0.3, k_ac == 1) %>% 
  ggplot(aes(x = k_ab, y = power, color = factor(OR_bc))) + geom_line(size = 1.5) + facet_wrap(~tau) + 
  labs(title = "pi_a = 0.3, k_ac = 1", color = "True OR_bc") + theme_bw()


c <- df %>% filter(pi_a == 0.1, k_ac == 5) %>% 
  ggplot(aes(x = k_ab, y = power, color = factor(OR_bc))) + geom_line(size = 1.5) + facet_wrap(~tau) + 
  labs(title = "pi_a = 0.1, k_ac = 5", color = "True OR_bc") + theme_bw()

d <- df %>% filter(pi_a == 0.3, k_ac == 5) %>% 
  ggplot(aes(x = k_ab, y = power, color = factor(OR_bc))) + geom_line(size = 1.5) + facet_wrap(~tau) + 
  labs(title = "pi_a = 0.3, k_ac = 5", color = "True OR_bc") + theme_bw()


gridExtra::grid.arrange(a,b,c,d)
```



```{r, fig.height=6, fig.width=8, out.width = "80%"}
a <- df_indirect %>% filter(pi_a == 0.1) %>% 
  ggplot(aes(x = k_ab, y = power, color = factor(OR_bc))) + geom_line(size = 1.5) + facet_wrap(~tau) + 
  labs(title = "pi_a = 0.1", color = "True OR_bc") + theme_bw()

b <- df_indirect %>% filter(pi_a == 0.3) %>% 
  ggplot(aes(x = k_ab, y = power, color = factor(OR_bc))) + geom_line(size = 1.5) + facet_wrap(~tau) + 
  labs(title = "pi_a = 0.3", color = "True OR_bc") + theme_bw()

c <- df_indirect %>% filter(pi_a == 0.5) %>% 
  ggplot(aes(x = k_ab, y = power, color = factor(OR_bc))) + geom_line(size = 1.5) + facet_wrap(~tau) + 
  labs(title = "pi_a = 0.5", color = "True OR_bc") + theme_bw()

gridExtra::grid.arrange(a,b,c)
```

```{r, fig.height=6, fig.width=8, out.width = "80%"}
a <- df_direct %>% filter(pi_a == 0.1) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc))) + geom_line(size = 1.5) + facet_wrap(~tau) + 
  labs(title = "pi_a = 0.1", color = "True OR_bc") + theme_bw()

b <- df_direct %>% filter(pi_a == 0.3) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc))) + geom_line(size = 1.5) + facet_wrap(~tau) + 
  labs(title = "pi_a = 0.3", color = "True OR_bc") + theme_bw()

c <- df_direct %>% filter(pi_a == 0.5) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc))) + geom_line(size = 1.5) + facet_wrap(~tau) + 
  labs(title = "pi_a = 0.5", color = "True OR_bc") + theme_bw()

gridExtra::grid.arrange(a,b,c)
```



```{r, fig.height=6, fig.width=8, out.width = "80%"}
a <- df_BNMA %>% filter(pi_a == 0.1) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc))) + geom_line(size = 1.5) + facet_wrap(~tau) + 
  labs(title = "pi_a = 0.1", color = "True OR_bc") + theme_bw()

b <- df_BNMA %>% filter(pi_a == 0.3) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc))) + geom_line(size = 1.5) + facet_wrap(~tau) + 
  labs(title = "pi_a = 0.3", color = "True OR_bc") + theme_bw()

c <- df_BNMA %>% filter(pi_a == 0.5) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc))) + geom_line(size = 1.5) + facet_wrap(~tau) + 
  labs(title = "pi_a = 0.5", color = "True OR_bc") + theme_bw()

gridExtra::grid.arrange(a,b,c)
```








