---
title: "Result"
author: "Yicheng Shen"
date: "2023-03-12"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = T, warning = F)
library(metafor)
library(tidyverse)
library(kableExtra)
library(foreach)
library(doParallel)
ggplot2::theme_set(ggplot2::theme_bw())
knitr::opts_chunk$set(out.width = "100%", fig.align = 'center')

# Initialize parallel backend
cl <- makeCluster(8)

# Register the parallel backend
registerDoParallel(cl)

source("power_simA.R")
source("power_simB.R")
source("power_simC.R")
```

```{r}
load("df_indirect.RData")
load("df_direct.RData")
```

```{r, fig.height=7, fig.width=10}
a <- df_indirect %>% filter(pi_a == 0.1) %>% 
  ggplot(aes(x = k_ab, y = power, color = factor(OR_bc))) + geom_line(size = 1.5) + geom_hline(yintercept =0.8) + facet_wrap(~tau) + labs(title = "pi_a = 0.1", color = "True OR_bc") 

b <- df_indirect %>% filter(pi_a == 0.3) %>% 
  ggplot(aes(x = k_ab, y = power, color = factor(OR_bc))) + geom_line(size = 1.5) + geom_hline(yintercept =0.8) + facet_wrap(~tau) +labs(title = "pi_a = 0.3", color = "True OR_bc")  

c <- df_indirect %>% filter(pi_a == 0.5) %>% 
  ggplot(aes(x = k_ab, y = power, color = factor(OR_bc))) + geom_line(size = 1.5) + geom_hline(yintercept =0.8) + facet_wrap(~tau) + labs(title = "pi_a = 0.5", color = "True OR_bc") 

gridExtra::grid.arrange(a,b,c)
```

```{r, fig.height=7, fig.width=10}
d <- df_direct %>% filter(pi_a == 0.1) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc))) + geom_line(size = 1.5) + geom_hline(yintercept =0.8) +
  facet_wrap(~tau) + labs(title = "pi_a = 0.1", color = "True OR_bc") + theme_bw()

e <- df_direct %>% filter(pi_a == 0.3) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc))) + geom_line(size = 1.5) + geom_hline(yintercept =0.8) +
  facet_wrap(~tau) + labs(title = "pi_a = 0.3", color = "True OR_bc") + theme_bw()

f <- df_direct %>% filter(pi_a == 0.5) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc))) + geom_line(size = 1.5) + geom_hline(yintercept =0.8) +
  facet_wrap(~tau) + labs(title = "pi_a = 0.5", color = "True OR_bc") + theme_bw()

gridExtra::grid.arrange(d,e,f)
```

```{r, fig.height=7, fig.width=12}
gridExtra::grid.arrange(a, d, b, e, c, f, ncol = 2)
```



```{r, fig.height=7, fig.width=10}
load("df_BNMA.RData")
a <- df_BNMA %>% filter(pi_a == 0.1) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc))) + geom_line(size = 1.5) + geom_hline(yintercept =0.8) +
  facet_wrap(~tau) + labs(title = "pi_a = 0.1", color = "True OR_bc") + theme_bw()

b <- df_BNMA %>% filter(pi_a == 0.3) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc))) + geom_line(size = 1.5) + geom_hline(yintercept =0.8) +
  facet_wrap(~tau) + labs(title = "pi_a = 0.3", color = "True OR_bc") + theme_bw()

c <- df_BNMA %>% filter(pi_a == 0.5) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc))) + geom_line(size = 1.5) + geom_hline(yintercept =0.8) +
  facet_wrap(~tau) +  labs(title = "pi_a = 0.5", color = "True OR_bc") + theme_bw()

gridExtra::grid.arrange(a,b,c)
```



# New settings

```{r}
load("df_NMA_new.RData")
load("df_indirect_new.RData")
load("df_direct_new.RData")

load("df_NMA_new_0.1.RData")
load("df_indirect_new_0.1.RData")
load("df_direct_new_0.1.RData")
```


```{r}
df_indirect_new

gridExtra::grid.arrange(

df_indirect_new %>% filter(k_ab == 6) %>% 
  ggplot(aes(x = k_ac, y = power, color = factor(OR_bc)))  + geom_hline(size = 1.2, aes(yintercept = power, color = factor(OR_bc))) +
  facet_wrap(~tau) + labs(title = "k_ab = k_ac = 6", color = "True OR_bc", x = "") + theme_bw() 
,
df_indirect_new %>% filter(k_ab == 12) %>% 
  ggplot(aes(x = k_ac, y = power, color = factor(OR_bc)))  + geom_hline(size = 1.2, aes(yintercept = power, color = factor(OR_bc))) +
  facet_wrap(~tau) + labs(title = "k_ab = k_ac = 12", color = "True OR_bc", x = "") + theme_bw()
)
```
```{r,fig.height=2.5, fig.width=12}
gridExtra::grid.arrange(

df_indirect_new %>% filter(k_ab == 6) %>% 
  ggplot(aes(x = k_ac, y = power, color = factor(OR_bc)))  + geom_hline(size = 1.2, aes(yintercept = power, color = factor(OR_bc))) +
  facet_wrap(~tau) + labs(title = "k_ab = k_ac = 6", color = "True OR_bc", x = "") + theme_bw() 
,
df_indirect_new %>% filter(k_ab == 12) %>% 
  ggplot(aes(x = k_ac, y = power, color = factor(OR_bc)))  + geom_hline(size = 1.2, aes(yintercept = power, color = factor(OR_bc))) +
  facet_wrap(~tau) + labs(title = "k_ab = k_ac = 12", color = "True OR_bc", x = "") + theme_bw()
,ncol = 2)
```


```{r, fig.height=5, fig.width=9}
df_direct_new

gridExtra::grid.arrange(

df_direct_new %>% filter(k_bc %in% c(1,2,3,6)) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc)))  + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "k_bc in c(1,2,3,6)", color = "True OR_bc") + theme_bw() + scale_x_continuous(breaks = seq(1, 6, 1), labels = as.character(seq(1, 6, 1)))
,
df_direct_new %>% filter(k_bc %in% c(2,4,6,12)) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc)))  + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "k_bc in c(2,4,6,12)", color = "True OR_bc") + theme_bw() + scale_x_continuous(breaks = seq(2, 12, 2), labels = as.character(seq(2, 12, 2)))
)
```

```{r, fig.height=5, fig.width=9}
# Compard direct and indirect evidence powers
gridExtra::grid.arrange(

df_direct_new %>% filter(k_bc %in% c(1,2,3,6)) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc)))  + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "k_ab = k_ac = 6", color = "True OR_bc") + theme_bw() + geom_hline(linetype = "dashed", data = df_indirect_new[which(df_indirect_new$k_ab==6),], aes(yintercept = power, color = factor(OR_bc))) + scale_x_continuous(breaks = seq(1, 6, 1), labels = as.character(seq(1, 6, 1)))
,
df_direct_new %>% filter(k_bc %in% c(2,4,6,12)) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc)))  + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "k_ab = k_ac = 12", color = "True OR_bc") + theme_bw()  + geom_hline(linetype = "dashed", data = df_indirect_new[which(df_indirect_new$k_ab==12),], aes(yintercept = power, color = factor(OR_bc))) + scale_x_continuous(breaks = seq(2, 12, 2), labels = as.character(seq(2, 12, 2)))
)
```



```{r, fig.height=5, fig.width=9}
# BNMA

a <- df_BNMA_new %>% filter(k_ab == 6) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc))) + geom_line(size = 1.5) + geom_hline(yintercept =0.8) +
  facet_wrap(~tau) + labs(title = "k_ab = k_ac = 6", color = "True OR_bc") + theme_bw()  + scale_x_continuous(breaks = seq(1, 6, 1), labels = as.character(seq(1, 6, 1)))
  
b <- df_BNMA_new %>% filter(k_ab == 12) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc))) + geom_line(size = 1.5) + geom_hline(yintercept =0.8) +
  facet_wrap(~tau) + labs(title = "k_ab = k_ac = 12", color = "True OR_bc") + theme_bw() + scale_x_continuous(breaks = seq(2, 12, 2), labels = as.character(seq(2, 12, 2)))

gridExtra::grid.arrange(a,b)
```


```{r, fig.height=5, fig.width=9}
# Compare BNMA and indirect evidence only

a <- df_BNMA_new %>% filter(k_ab == 6) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc))) + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "k_ab = k_ac = 6", color = "True OR_bc") + theme_bw() + geom_hline(linetype = "dashed", data = df_indirect_new[which(df_indirect_new$k_ab==6),], aes(yintercept = power, color = factor(OR_bc)))+ scale_x_continuous(breaks = seq(1, 6, 1), labels = as.character(seq(1, 6, 1)))


b <- df_BNMA_new %>% filter(k_ab == 12) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc))) + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "k_ab = k_ac = 12", color = "True OR_bc") + theme_bw()  + geom_hline(linetype = "dashed", data = df_indirect_new[which(df_indirect_new$k_ab==12),], aes(yintercept = power, color = factor(OR_bc)))+ scale_x_continuous(breaks = seq(2, 12, 2), labels = as.character(seq(2, 12, 2)))

gridExtra::grid.arrange(a,b)
```


```{r, fig.height=5, fig.width=9}
# Compare BNMA and direct evidence only

a <- df_BNMA_new %>% filter(k_ab == 6) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc))) + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "k_ab = k_ac = 6", color = "True OR_bc") + theme_bw() + geom_line(linetype = "dashed", data = df_direct_new[which(df_direct_new$k_bc %in% c(1,2,3,6)),], aes(y = power, x = k_bc, color = factor(OR_bc)))+ scale_x_continuous(breaks = seq(1, 6, 1), labels = as.character(seq(1, 6, 1)))
  

b <- df_BNMA_new %>% filter(k_ab == 12) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc))) + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "k_ab = k_ac = 12", color = "True OR_bc") + theme_bw()  + geom_line(linetype = "dashed", data = df_direct_new[which(df_direct_new$k_bc %in% c(2,4,6,12)),], aes(y = power, x = k_bc, color = factor(OR_bc)))+ scale_x_continuous(breaks = seq(2, 12, 2), labels = as.character(seq(2, 12, 2)))

gridExtra::grid.arrange(a,b)
```


```{r, fig.height=5, fig.width=12}
a <- df_BNMA_new %>% filter(k_ab == 6) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc))) + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "k_ab = k_ac = 6", color = "True OR_bc") + theme_bw() + geom_hline(linetype = "dashed", data = df_indirect_new[which(df_indirect_new$k_ab==6),], aes(yintercept = power, color = factor(OR_bc))) + scale_x_continuous(breaks = seq(1, 6, 1), labels = as.character(seq(1, 6, 1)))
  

b <- df_BNMA_new %>% filter(k_ab == 12) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc))) + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "k_ab = k_ac = 12", color = "True OR_bc") + theme_bw()  + geom_hline(linetype = "dashed", data = df_indirect_new[which(df_indirect_new$k_ab==12),], aes(yintercept = power, color = factor(OR_bc))) + scale_x_continuous(breaks = seq(2, 12, 2), labels = as.character(seq(2, 12, 2)))


c <- df_BNMA_new %>% filter(k_ab == 6) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc))) + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "k_ab = k_ac = 6", color = "True OR_bc") + theme_bw() + geom_line(linetype = "dotdash", data = df_direct_new[which(df_direct_new$k_bc %in% c(1,2,3,6)),], aes(y = power, x = k_bc, color = factor(OR_bc)))+ scale_x_continuous(breaks = seq(1, 6, 1), labels = as.character(seq(1, 6, 1)))
  

d <- df_BNMA_new %>% filter(k_ab == 12) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc))) + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "k_ab = k_ac = 12", color = "True OR_bc") + theme_bw() + geom_line(linetype = "dotdash", data = df_direct_new[which(df_direct_new$k_bc %in% c(2,4,6,12)),], aes(y = power, x = k_bc, color = factor(OR_bc)))+ scale_x_continuous(breaks = seq(2, 12, 2), labels = as.character(seq(2, 12, 2)))

gridExtra::grid.arrange(a,b,c,d,ncol = 2)
```


<!-- # specifcs -->

<!-- 6 6  -->
<!-- 1 -->
<!-- 6 6 1  -->
<!-- OR_bc = 1.17 -->
<!-- ```{r} -->
<!-- power.sim_indirect(S = 1000, k_ab=6, k_ac=6, pi_a = 0.5, OR_ab =1.2, OR_ac=1.4, tau=0.4,verbose = F) -->
<!-- power.sim_direct(S = 1000, k_bc=1, pi_a = 0.5, OR_ab =1.2, OR_ac=1.4, tau=0.4,verbose = F) -->
<!-- power.sim.NMA(S = 200, k_ab = 6, k_ac = 6, k_bc = 1, pi_a = 0.5, OR_ab = 1.2, OR_ac = 1.4, tau = 0.4) -->
<!-- ``` -->

<!-- 6 6 -->
<!-- 2 -->
<!-- 6 6 2 -->
<!-- OR_bc = 1.33 -->
<!-- ```{r} -->
<!-- power.sim_indirect(S = 1000, k_ab=6, k_ac=6, pi_a = 0.5, OR_ab =1.2, OR_ac=1.6, tau=0.2,verbose = F) -->
<!-- power.sim_direct(S = 1000, k_bc=2, pi_a = 0.5, OR_ab =1.2, OR_ac=1.6, tau=0.2,verbose = F) -->
<!-- power.sim.NMA(S = 200, k_ab = 6, k_ac = 6, k_bc = 2, pi_a = 0.5, OR_ab = 1.2, OR_ac = 1.6, tau = 0.2) -->
<!-- ``` -->


<!-- 6 6  -->
<!-- 6 -->
<!-- 6 6 6 -->
<!-- OR_bc = 1.5 -->
<!-- ```{r} -->
<!-- power.sim_indirect(S = 1000, k_ab=6, k_ac=6, pi_a = 0.5, OR_ab =1.2, OR_ac=1.8, tau=0.2,verbose = F) -->
<!-- power.sim_direct(S = 1000, k_bc=6, pi_a = 0.5, OR_ab =1.2, OR_ac=1.8, tau=0.2,verbose = F) -->
<!-- power.sim.NMA(S = 200, k_ab = 6, k_ac = 6, k_bc = 6, pi_a = 0.5, OR_ab = 1.2, OR_ac = 1.8, tau = 0.2) -->
<!-- ``` -->


<!-- 12 12 -->
<!-- 12 -->
<!-- 12 12 12 -->
<!-- OR_bc = 1.33 -->
<!-- ```{r} -->
<!-- power.sim_indirect(S = 1000, k_ab=12, k_ac=12, pi_a = 0.5, OR_ab =1.2, OR_ac=1.6, tau=0.2,verbose = F) -->
<!-- power.sim_direct(S = 1000, k_bc=12, pi_a = 0.5, OR_ab =1.2, OR_ac=1.6, tau=0.2,verbose = F) -->
<!-- power.sim.NMA(S = 200, k_ab = 12, k_ac = 12, k_bc = 12, pi_a = 0.5, OR_ab = 1.2, OR_ac = 1.6, tau = 0.2) -->
<!-- ``` -->




# specific

```{r}
df_indirect_new %>% filter(k_ab == 6, k_ac == 6, pi_a == 0.5, OR_ab == 1.2, OR_ac == 1.4, tau == 0.4) %>% ungroup() %>% select(power)
df_direct_new %>% filter(k_bc == 2, pi_a == 0.5, OR_ab == 1.2, OR_ac == 1.4, tau == 0.4) %>% ungroup() %>% select(power)
df_BNMA_new %>% filter(k_ab == 6, k_ac == 6, k_bc == 2, pi_a == 0.5, OR_ab == 1.2, OR_ac == 1.4, tau == 0.4) %>% ungroup() %>% select(power)
```


```{r}
df_indirect_new %>% filter(k_ab == 6, k_ac == 6, pi_a == 0.5, OR_ab == 1.2, OR_ac == 1.6, tau == 0.2) %>% ungroup() %>% select(power)
df_direct_new %>% filter(k_bc == 2, pi_a == 0.5, OR_ab == 1.2, OR_ac == 1.6, tau == 0.2) %>% ungroup() %>% select(power)
df_BNMA_new %>% filter(k_ab == 6, k_ac == 6, k_bc == 2, pi_a == 0.5, OR_ab == 1.2, OR_ac == 1.6, tau == 0.2) %>% ungroup() %>% select(power)
```


```{r}
df_indirect_new %>% filter(k_ab == 6, k_ac == 6, OR_ab == 1.2, OR_ac == 1.6, tau == 0.2) %>% ungroup() %>% select(power)
df_direct_new %>% filter(k_bc == 6, OR_ab == 1.2, OR_ac == 1.6, tau == 0.2) %>% ungroup() %>% select(power)
df_BNMA_new %>% filter(k_ab == 6, k_ac == 6, k_bc == 6, OR_ab == 1.2, OR_ac == 1.6, tau == 0.2) %>% ungroup() %>% select(power)
```



