---
title: "Result"
author: "Yicheng Shen"
date: "2023-04-05"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = T, warning = F)
library(metafor)
library(tidyverse)
library(kableExtra)
library(foreach)
library(doParallel)
ggplot2::theme_set(ggplot2::theme_bw())
knitr::opts_chunk$set(out.width = "100%", fig.align = 'center')

# Initialize parallel backend
cl <- makeCluster(8)

# Register the parallel backend
registerDoParallel(cl)
```

### All bayesian gemtc

```{r}
load("df_indirect_BNMA.RData")
load("df_direct_BNMA.RData")
load("df_overall_BNMA.RData")
```

```{r, fig.height=5.5, fig.width=12}
# power in indirect evidence
gridExtra::grid.arrange(

df_indirect_new %>% filter(k_ab == 6, pi_a == 0.1) %>% 
  ggplot(aes(x = k_ac, y = power, color = factor(OR_bc)))  + geom_hline(size = 1.2, aes(yintercept = power, color = factor(OR_bc))) +
  facet_wrap(~tau) + labs(title = "Indirect Evi: k_ab = k_ac = 6, pi_a = 0.1", color = "True OR_bc", x = "") + theme_bw() 
,
df_indirect_new %>% filter(k_ab == 12, pi_a == 0.1) %>% 
  ggplot(aes(x = k_ac, y = power, color = factor(OR_bc)))  + geom_hline(size = 1.2, aes(yintercept = power, color = factor(OR_bc))) +
  facet_wrap(~tau) + labs(title = "Indirect Evi: k_ab = k_ac = 12, pi_a = 0.1", color = "True OR_bc", x = "") + theme_bw()

,

df_indirect_new %>% filter(k_ab == 6, pi_a == 0.5) %>% 
  ggplot(aes(x = k_ac, y = power, color = factor(OR_bc)))  + geom_hline(size = 1.2, aes(yintercept = power, color = factor(OR_bc))) +
  facet_wrap(~tau) + labs(title = "Indirect Evi: k_ab = k_ac = 6, pi_a = 0.5", color = "True OR_bc", x = "") + theme_bw() 
,
df_indirect_new %>% filter(k_ab == 12, pi_a == 0.5) %>% 
  ggplot(aes(x = k_ac, y = power, color = factor(OR_bc)))  + geom_hline(size = 1.2, aes(yintercept = power, color = factor(OR_bc))) +
  facet_wrap(~tau) + labs(title = "Indirect Evi: k_ab = k_ac = 12, pi_a = 0.5", color = "True OR_bc", x = "") + theme_bw()
)

```

```{r, fig.height=5.5, fig.width=12}

# ranking correct in indirect evidence

gridExtra::grid.arrange(

df_indirect_new %>% filter(k_ab == 6, pi_a == 0.1) %>% 
  ggplot(aes(x = k_ac, y = rank_correct, color = factor(OR_bc)))  + geom_hline(size = 1.2, aes(yintercept = rank_correct, color = factor(OR_bc))) +
  facet_wrap(~tau) + labs(title = "Indirect Evi: k_ab = k_ac = 6, pi_a = 0.1", color = "True OR_bc", x = "") + theme_bw() 
,
df_indirect_new %>% filter(k_ab == 12, pi_a == 0.1) %>% 
  ggplot(aes(x = k_ac, y = rank_correct, color = factor(OR_bc)))  + geom_hline(size = 1.2, aes(yintercept = rank_correct, color = factor(OR_bc))) +
  facet_wrap(~tau) + labs(title = "Indirect Evi: k_ab = k_ac = 12, pi_a = 0.1", color = "True OR_bc", x = "") + theme_bw()

,

df_indirect_new %>% filter(k_ab == 6, pi_a == 0.5) %>% 
  ggplot(aes(x = k_ac, y = rank_correct, color = factor(OR_bc)))  + geom_hline(size = 1.2, aes(yintercept = rank_correct, color = factor(OR_bc))) +
  facet_wrap(~tau) + labs(title = "Indirect Evi: k_ab = k_ac = 6, pi_a = 0.5", color = "True OR_bc", x = "") + theme_bw() 
,
df_indirect_new %>% filter(k_ab == 12, pi_a == 0.5) %>% 
  ggplot(aes(x = k_ac, y = rank_correct, color = factor(OR_bc)))  + geom_hline(size = 1.2, aes(yintercept = rank_correct, color = factor(OR_bc))) +
  facet_wrap(~tau) + labs(title = "Indirect Evi: k_ab = k_ac = 12, pi_a = 0.5", color = "True OR_bc", x = "") + theme_bw()
)
```

```{r, fig.height=5.5, fig.width=12}

### Power 

gridExtra::grid.arrange(

df_direct_new %>% filter(k_bc %in% c(1,2,3,6), pi_a == 0.1) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc)))  + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Direct Evi: k_bc in c(1,2,3,6), pi_a = 0.1", color = "True OR_bc") + theme_bw() + scale_x_continuous(breaks = seq(1, 6, 1), labels = as.character(seq(1, 6, 1)))

,
df_direct_new %>% filter(k_bc %in% c(2,4,6,12), pi_a == 0.1) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc)))  + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Direct Evi: k_bc in c(2,4,6,12), pi_a = 0.1", color = "True OR_bc") + theme_bw() + scale_x_continuous(breaks = seq(2, 12, 2), labels = as.character(seq(2, 12, 2)))

,

df_direct_new %>% filter(k_bc %in% c(1,2,3,6), pi_a == 0.5) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc)))  + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Direct Evi: k_bc in c(1,2,3,6), pi_a = 0.5", color = "True OR_bc") + theme_bw() + scale_x_continuous(breaks = seq(1, 6, 1), labels = as.character(seq(1, 6, 1)))

,
df_direct_new %>% filter(k_bc %in% c(2,4,6,12), pi_a == 0.5) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc)))  + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Direct Evi:  k_bc in c(2,4,6,12), pi_a = 0.5", color = "True OR_bc") + theme_bw() + scale_x_continuous(breaks = seq(2, 12, 2), labels = as.character(seq(2, 12, 2)))
)

```


```{r, fig.height=5.5, fig.width=12}

### Rank Correct

gridExtra::grid.arrange(

df_direct_new %>% filter(k_bc %in% c(1,2,3,6), pi_a == 0.1) %>% 
  ggplot(aes(x = k_bc, y = rank_correct, color = factor(OR_bc)))  + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Direct Evi: k_bc in c(1,2,3,6), pi_a = 0.1", color = "True OR_bc") + theme_bw() + scale_x_continuous(breaks = seq(1, 6, 1), labels = as.character(seq(1, 6, 1)))

,
df_direct_new %>% filter(k_bc %in% c(2,4,6,12), pi_a == 0.1) %>% 
  ggplot(aes(x = k_bc, y = rank_correct, color = factor(OR_bc)))  + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Direct Evi: k_bc in c(2,4,6,12), pi_a = 0.1", color = "True OR_bc") + theme_bw() + scale_x_continuous(breaks = seq(2, 12, 2), labels = as.character(seq(2, 12, 2)))

,

df_direct_new %>% filter(k_bc %in% c(1,2,3,6), pi_a == 0.5) %>% 
  ggplot(aes(x = k_bc, y = rank_correct, color = factor(OR_bc)))  + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Direct Evi: k_bc in c(1,2,3,6), pi_a = 0.5", color = "True OR_bc") + theme_bw() + scale_x_continuous(breaks = seq(1, 6, 1), labels = as.character(seq(1, 6, 1)))

,
df_direct_new %>% filter(k_bc %in% c(2,4,6,12), pi_a == 0.5) %>% 
  ggplot(aes(x = k_bc, y = rank_correct, color = factor(OR_bc)))  + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Direct Evi:  k_bc in c(2,4,6,12), pi_a = 0.5", color = "True OR_bc") + theme_bw() + scale_x_continuous(breaks = seq(2, 12, 2), labels = as.character(seq(2, 12, 2)))
)
```


```{r, fig.height=5.5, fig.width=12}
# Compare direct and indirect evidence powers

gridExtra::grid.arrange(

df_direct_new %>% filter(k_bc %in% c(1,2,3,6), pi_a == 0.1) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc)))  + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Direct (k_bc) vs Indirect (k_ab = k_ac = 6), pi_a = 0.1", color = "True OR_bc") + theme_bw() + geom_hline(linetype = "dashed", data = df_indirect_new %>% filter(k_ab == 6, pi_a == 0.1), aes(yintercept = power, color = factor(OR_bc))) + scale_x_continuous(breaks = seq(1, 6, 1), labels = as.character(seq(1, 6, 1)))
,
df_direct_new %>% filter(k_bc %in% c(2,4,6,12), pi_a == 0.1) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc)))  + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Direct (k_bc) vs Indirect (k_ab = k_ac = 12), pi_a = 0.1", color = "True OR_bc") + theme_bw()  + geom_hline(linetype = "dashed", data = df_indirect_new %>% filter(k_ab == 12, pi_a == 0.1), aes(yintercept = power, color = factor(OR_bc))) + scale_x_continuous(breaks = seq(2, 12, 2), labels = as.character(seq(2, 12, 2)))

,

df_direct_new %>% filter(k_bc %in% c(1,2,3,6), pi_a == 0.5) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc)))  + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Direct (k_bc) vs Indirect (k_ab = k_ac = 6), pi_a = 0.5", color = "True OR_bc") + theme_bw() + geom_hline(linetype = "dashed", data = df_indirect_new %>% filter(k_ab == 6, pi_a == 0.5), aes(yintercept = power, color = factor(OR_bc))) + scale_x_continuous(breaks = seq(1, 6, 1), labels = as.character(seq(1, 6, 1)))
,
df_direct_new %>% filter(k_bc %in% c(2,4,6,12), pi_a == 0.5) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc)))  + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Direct (k_bc) vs Indirect (k_ab = k_ac = 12), pi_a = 0.5", color = "True OR_bc") + theme_bw()  + geom_hline(linetype = "dashed", data = df_indirect_new %>% filter(k_ab == 12, pi_a == 0.5), aes(yintercept = power, color = factor(OR_bc))) + scale_x_continuous(breaks = seq(2, 12, 2), labels = as.character(seq(2, 12, 2)))
)
```





```{r, fig.height=5.5, fig.width=12}
# Compare direct and indirect evidence rank

gridExtra::grid.arrange(

df_direct_new %>% filter(k_bc %in% c(1,2,3,6), pi_a == 0.1) %>% 
  ggplot(aes(x = k_bc, y = rank_correct, color = factor(OR_bc)))  + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Direct (k_bc) vs Indirect (k_ab = k_ac = 6), pi_a = 0.1", color = "True OR_bc") + theme_bw() + geom_hline(linetype = "dashed", data = df_indirect_new %>% filter(k_ab == 6, pi_a == 0.1), aes(yintercept = rank_correct, color = factor(OR_bc))) + scale_x_continuous(breaks = seq(1, 6, 1), labels = as.character(seq(1, 6, 1)))
,
df_direct_new %>% filter(k_bc %in% c(2,4,6,12), pi_a == 0.1) %>% 
  ggplot(aes(x = k_bc, y = rank_correct, color = factor(OR_bc)))  + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Direct (k_bc) vs Indirect (k_ab = k_ac = 12), pi_a = 0.1", color = "True OR_bc") + theme_bw()  + geom_hline(linetype = "dashed", data = df_indirect_new %>% filter(k_ab == 12, pi_a == 0.1), aes(yintercept = rank_correct, color = factor(OR_bc))) + scale_x_continuous(breaks = seq(2, 12, 2), labels = as.character(seq(2, 12, 2)))
,

df_direct_new %>% filter(k_bc %in% c(1,2,3,6), pi_a == 0.5) %>% 
  ggplot(aes(x = k_bc, y = rank_correct, color = factor(OR_bc)))  + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Direct (k_bc) vs Indirect (k_ab = k_ac = 6), pi_a = 0.5", color = "True OR_bc") + theme_bw() + geom_hline(linetype = "dashed", data = df_indirect_new %>% filter(k_ab == 6, pi_a == 0.5), aes(yintercept = rank_correct, color = factor(OR_bc))) + scale_x_continuous(breaks = seq(1, 6, 1), labels = as.character(seq(1, 6, 1)))
,
df_direct_new %>% filter(k_bc %in% c(2,4,6,12), pi_a == 0.5) %>% 
  ggplot(aes(x = k_bc, y = rank_correct, color = factor(OR_bc)))  + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Direct (k_bc) vs Indirect (k_ab = k_ac = 12), pi_a = 0.5", color = "True OR_bc") + theme_bw()  + geom_hline(linetype = "dashed", data = df_indirect_new %>% filter(k_ab == 12, pi_a == 0.5), aes(yintercept = rank_correct, color = factor(OR_bc))) + scale_x_continuous(breaks = seq(2, 12, 2), labels = as.character(seq(2, 12, 2)))
)
```


```{r, fig.height=5.5, fig.width=12}
load("df_indirect_BNMA.RData")
load("df_direct_BNMA.RData")
load("df_overall_BNMA.RData")

df_indirect_new = df_indirect_new[which(df_indirect_new$pi_a==0.1),]
df_direct_new = df_direct_new[which(df_direct_new$pi_a==0.1),]
df_BNMA_new =  df_BNMA_new[which(df_BNMA_new$pi_a==0.1),]

a <- df_BNMA_new %>% filter(k_ab == 6) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc))) + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Overall vs Only Indirect (k_ab = k_ac = 6)", color = "True OR_bc") + theme_bw() + geom_hline(linetype = "dashed", data = df_indirect_new[which(df_indirect_new$k_ab==6),], aes(yintercept = power, color = factor(OR_bc))) + scale_x_continuous(breaks = seq(1, 6, 1), labels = as.character(seq(1, 6, 1)))
  

b <- df_BNMA_new %>% filter(k_ab == 12) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc))) + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Overall vs Only Indirect (k_ab = k_ac = 12)", color = "True OR_bc") + theme_bw()  + geom_hline(linetype = "dashed", data = df_indirect_new[which(df_indirect_new$k_ab==12),], aes(yintercept = power, color = factor(OR_bc))) + scale_x_continuous(breaks = seq(2, 12, 2), labels = as.character(seq(2, 12, 2)))


c <- df_BNMA_new %>% filter(k_ab == 6) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc))) + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Overall vs Only Direct (k_bc = 1, 2, 3, 6)", color = "True OR_bc") + theme_bw() + geom_line(linetype = "dotdash", data = df_direct_new[which(df_direct_new$k_bc %in% c(1,2,3,6)),], aes(y = power, x = k_bc, color = factor(OR_bc)))+ scale_x_continuous(breaks = seq(1, 6, 1), labels = as.character(seq(1, 6, 1)))
  

d <- df_BNMA_new %>% filter(k_ab == 12) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc))) + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Overall vs Only Direct (k_bc = 2, 4, 6, 12)", color = "True OR_bc") + theme_bw() + geom_line(linetype = "dotdash", data = df_direct_new[which(df_direct_new$k_bc %in% c(2,4,6,12)),], aes(y = power, x = k_bc, color = factor(OR_bc)))+ scale_x_continuous(breaks = seq(2, 12, 2), labels = as.character(seq(2, 12, 2)))

gridExtra::grid.arrange(a,b,c,d,ncol = 2)
```



```{r, fig.height=5.5, fig.width=12}
load("df_indirect_BNMA.RData")
load("df_direct_BNMA.RData")
load("df_overall_BNMA.RData")

df_indirect_new = df_indirect_new[which(df_indirect_new$pi_a==0.5),]
df_direct_new = df_direct_new[which(df_direct_new$pi_a==0.5),]
df_BNMA_new =  df_BNMA_new[which(df_BNMA_new$pi_a==0.5),]

a <- df_BNMA_new %>% filter(k_ab == 6) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc))) + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Overall vs Only Indirect (k_ab = k_ac = 6)", color = "True OR_bc") + theme_bw() + geom_hline(linetype = "dashed", data = df_indirect_new[which(df_indirect_new$k_ab==6),], aes(yintercept = power, color = factor(OR_bc))) + scale_x_continuous(breaks = seq(1, 6, 1), labels = as.character(seq(1, 6, 1)))
  

b <- df_BNMA_new %>% filter(k_ab == 12) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc))) + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Overall vs Only Indirect (k_ab = k_ac = 12)", color = "True OR_bc") + theme_bw()  + geom_hline(linetype = "dashed", data = df_indirect_new[which(df_indirect_new$k_ab==12),], aes(yintercept = power, color = factor(OR_bc))) + scale_x_continuous(breaks = seq(2, 12, 2), labels = as.character(seq(2, 12, 2)))


c <- df_BNMA_new %>% filter(k_ab == 6) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc))) + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Overall vs Only Direct (k_bc = 1, 2, 3, 6)", color = "True OR_bc") + theme_bw() + geom_line(linetype = "dotdash", data = df_direct_new[which(df_direct_new$k_bc %in% c(1,2,3,6)),], aes(y = power, x = k_bc, color = factor(OR_bc)))+ scale_x_continuous(breaks = seq(1, 6, 1), labels = as.character(seq(1, 6, 1)))
  

d <- df_BNMA_new %>% filter(k_ab == 12) %>% 
  ggplot(aes(x = k_bc, y = power, color = factor(OR_bc))) + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Overall vs Only Direct (k_bc = 2, 4, 6, 12)", color = "True OR_bc") + theme_bw() + geom_line(linetype = "dotdash", data = df_direct_new[which(df_direct_new$k_bc %in% c(2,4,6,12)),], aes(y = power, x = k_bc, color = factor(OR_bc)))+ scale_x_continuous(breaks = seq(2, 12, 2), labels = as.character(seq(2, 12, 2)))

gridExtra::grid.arrange(a,b,c,d,ncol = 2)
```



```{r, fig.height=5.5, fig.width=12}
load("df_indirect_BNMA.RData")
load("df_direct_BNMA.RData")
load("df_overall_BNMA.RData")

df_indirect_new = df_indirect_new[which(df_indirect_new$pi_a==0.1),]
df_direct_new = df_direct_new[which(df_direct_new$pi_a==0.1),]
df_BNMA_new =  df_BNMA_new[which(df_BNMA_new$pi_a==0.1),]

a <- df_BNMA_new %>% filter(k_ab == 6) %>% 
  ggplot(aes(x = k_bc, y = rank_correct, color = factor(OR_bc))) + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Overall vs Only Indirect (k_ab = k_ac = 6)", color = "True OR_bc") + theme_bw() + geom_hline(linetype = "dashed", data = df_indirect_new[which(df_indirect_new$k_ab==6),], aes(yintercept = rank_correct, color = factor(OR_bc))) + scale_x_continuous(breaks = seq(1, 6, 1), labels = as.character(seq(1, 6, 1)))
  

b <- df_BNMA_new %>% filter(k_ab == 12) %>% 
  ggplot(aes(x = k_bc, y = rank_correct, color = factor(OR_bc))) + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Overall vs Only Indirect (k_ab = k_ac = 12)", color = "True OR_bc") + theme_bw()  + geom_hline(linetype = "dashed", data = df_indirect_new[which(df_indirect_new$k_ab==12),], aes(yintercept = rank_correct, color = factor(OR_bc))) + scale_x_continuous(breaks = seq(2, 12, 2), labels = as.character(seq(2, 12, 2)))


c <- df_BNMA_new %>% filter(k_ab == 6) %>% 
  ggplot(aes(x = k_bc, y = rank_correct, color = factor(OR_bc))) + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Overall vs Only Direct (k_bc = 1, 2, 3, 6)", color = "True OR_bc") + theme_bw() + geom_line(linetype = "dotdash", data = df_direct_new[which(df_direct_new$k_bc %in% c(1,2,3,6)),], aes(y = rank_correct, x = k_bc, color = factor(OR_bc)))+ scale_x_continuous(breaks = seq(1, 6, 1), labels = as.character(seq(1, 6, 1)))
  

d <- df_BNMA_new %>% filter(k_ab == 12) %>% 
  ggplot(aes(x = k_bc, y = rank_correct, color = factor(OR_bc))) + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Overall vs Only Direct (k_bc = 2, 4, 6, 12)", color = "True OR_bc") + theme_bw() + geom_line(linetype = "dotdash", data = df_direct_new[which(df_direct_new$k_bc %in% c(2,4,6,12)),], aes(y = rank_correct, x = k_bc, color = factor(OR_bc)))+ scale_x_continuous(breaks = seq(2, 12, 2), labels = as.character(seq(2, 12, 2)))

gridExtra::grid.arrange(a,b,c,d,ncol = 2)
```

# Anormaly in the correct ranking probability between overall and direct evdience. 


```{r, fig.height=5.5, fig.width=12}
load("df_indirect_BNMA.RData")
load("df_direct_BNMA.RData")
load("df_overall_BNMA.RData")

df_indirect_new = df_indirect_new[which(df_indirect_new$pi_a==0.5),]
df_direct_new = df_direct_new[which(df_direct_new$pi_a==0.5),]
df_BNMA_new =  df_BNMA_new[which(df_BNMA_new$pi_a==0.5),]

a <- df_BNMA_new %>% filter(k_ab == 6) %>% 
  ggplot(aes(x = k_bc, y = rank_correct, color = factor(OR_bc))) + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Overall vs Only Indirect (k_ab = k_ac = 6)", color = "True OR_bc") + theme_bw() + geom_hline(linetype = "dashed", data = df_indirect_new[which(df_indirect_new$k_ab==6),], aes(yintercept = rank_correct, color = factor(OR_bc))) + scale_x_continuous(breaks = seq(1, 6, 1), labels = as.character(seq(1, 6, 1)))
  

b <- df_BNMA_new %>% filter(k_ab == 12) %>% 
  ggplot(aes(x = k_bc, y = rank_correct, color = factor(OR_bc))) + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Overall vs Only Indirect (k_ab = k_ac = 12)", color = "True OR_bc") + theme_bw()  + geom_hline(linetype = "dashed", data = df_indirect_new[which(df_indirect_new$k_ab==12),], aes(yintercept = rank_correct, color = factor(OR_bc))) + scale_x_continuous(breaks = seq(2, 12, 2), labels = as.character(seq(2, 12, 2)))


c <- df_BNMA_new %>% filter(k_ab == 6) %>% 
  ggplot(aes(x = k_bc, y = rank_correct, color = factor(OR_bc))) + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Overall vs Only Direct (k_bc = 1, 2, 3, 6)", color = "True OR_bc") + theme_bw() + geom_line(linetype = "dotdash", data = df_direct_new[which(df_direct_new$k_bc %in% c(1,2,3,6)),], aes(y = rank_correct, x = k_bc, color = factor(OR_bc)))+ scale_x_continuous(breaks = seq(1, 6, 1), labels = as.character(seq(1, 6, 1)))
  

d <- df_BNMA_new %>% filter(k_ab == 12) %>% 
  ggplot(aes(x = k_bc, y = rank_correct, color = factor(OR_bc))) + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Overall vs Only Direct (k_bc =2, 4, 6, 12)", color = "True OR_bc") + theme_bw() + geom_line(linetype = "dotdash", data = df_direct_new[which(df_direct_new$k_bc %in% c(2,4,6,12)),], aes(y = rank_correct, x = k_bc, color = factor(OR_bc)))+ scale_x_continuous(breaks = seq(2, 12, 2), labels = as.character(seq(2, 12, 2)))

gridExtra::grid.arrange(a,b,c,d,ncol = 2)
```






