---
title: "Result"
author: "Yicheng Shen"
date: "2023-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, cache = F, error = F, warning = F, eval = T, message = F)
library(metafor)
library(tidyverse)
library(kableExtra)
library(latex2exp)
library(gridExtra)
ggplot2::theme_set(ggplot2::theme_bw())
knitr::opts_chunk$set(out.width = "100%", fig.align = 'center')
```

```{r}
Network1 = readRDS("NMA_Net1_res.rds")
Network2 = readRDS("NMA_Net2_res.rds")
Network3 = readRDS("NMA_Net3_res.rds")
Network4 = readRDS("NMA_Net4_res.rds")
Network5 = readRDS("NMA_Net5_res.rds")
Network6 = readRDS("NMA_Net6_res.rds")
```


```{r}
Network1 <- Network1 %>%
  mutate(tau = case_when( tau == 0.001 ~ "τ = 0.001", tau == 0.2 ~ "τ = 0.2", tau == 0.4 ~ "τ = 0.4", TRUE ~ as.character(tau)))

Network2 <- Network2 %>%
  mutate(tau = case_when( tau == 0.001 ~ "τ = 0.001", tau == 0.2 ~ "τ = 0.2", tau == 0.4 ~ "τ = 0.4", TRUE ~ as.character(tau)))

Network3 <- Network3 %>%
  mutate(tau = case_when( tau == 0.001 ~ "τ = 0.001", tau == 0.2 ~ "τ = 0.2", tau == 0.4 ~ "τ = 0.4", TRUE ~ as.character(tau)))

Network4 <- Network4 %>%
  mutate(tau = case_when( tau == 0.001 ~ "τ = 0.001", tau == 0.2 ~ "τ = 0.2", tau == 0.4 ~ "τ = 0.4", TRUE ~ as.character(tau)))

Network5 <- Network5 %>%
  mutate(tau = case_when( tau == 0.001 ~ "τ = 0.001", tau == 0.2 ~ "τ = 0.2", tau == 0.4 ~ "τ = 0.4", TRUE ~ as.character(tau)))

Network6 <- Network6 %>%
  mutate(tau = case_when( tau == 0.001 ~ "τ = 0.001", tau == 0.2 ~ "τ = 0.2", tau == 0.4 ~ "τ = 0.4", TRUE ~ as.character(tau)))
```


```{r}
Network6_sub = Network6
Network5_sub = Network5 
Network4_sub = Network4
Network3_sub = Network3 
Network2_sub = Network2 
Network1_sub = Network1 
```



```{r, fig.width=12, fig.height=4}
simple_power = Network6_sub %>% 
  ggplot() + facet_wrap(~tau) + 
  geom_line(data = Network1_sub, aes(x = k_ab, y = 1-power, color = "Network 1: Open loop (add partial indirect)"), size = 1) + 
  geom_line(data = Network2_sub, aes(x = k_ab, y = 1-power, color = "Network 2: Open loop (add full indirect)"), size = 1) +
  geom_line(data = Network3_sub, aes(x = k_bc, y = 1-power, color = "Network 3: Open loop (add direct)"), size = 1) + 
  geom_line(data = Network4_sub, aes(x = k_ac, y = 1-power, color = "Network 4: Closed loop (add partial indirect)"), size = 1) + 
  geom_line(data = Network5_sub, aes(x = k_ac, y = 1-power, color = "Network 5: Closed loop (add full indirect)"), size = 1) + 
  geom_line(aes(x = k_bc, y = 1-power, color = "Network 6: Closed loop (add direct)"), size = 1) + 
  scale_color_manual(name = "Types of Evidence Cycle", values = c(1,2,3,4,5,6)) +
  labs(title = TeX("(a) Closed Loop vs. Only Direct Evidence vs. Only Indirect Evidence"), y = "Power", x = "Numbers of Additional Studies") + scale_x_continuous(breaks = seq(1, 12, 2), labels = as.character(seq(1, 12, 2))) 

simple_power
```

