---
title: "Result"
author: "Yicheng Shen"
date: "2023-04-05"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = T, warning = F)
library(metafor)
library(tidyverse)
library(kableExtra)
library(latex2exp)
ggplot2::theme_set(ggplot2::theme_bw())
knitr::opts_chunk$set(out.width = "100%", fig.align = 'center')
```

### All bayesian gemtc

```{r}
load("df_indirect_BNMA_AB_bias3.RData")
load("df_direct_BNMA_AB_bias3.RData")
load("df_overall_BNMA_AB_bias3.RData")
```


```{r, fig.height=5.5, fig.width=12}
# power_het_eqcor in indirect evidence
gridExtra::grid.arrange(

df_indirect_new %>% filter(k_ab == 6, pi_a == 0.1) %>% 
  ggplot(aes(x = k_ac, y = power_het_eqcor, color = factor(OR_bc)))  + 
  geom_hline(size = 1.2, linetype = 1, aes(yintercept = power_het_eqcor, color = factor(OR_bc))) +
  facet_wrap(~tau) + labs(title = TeX("Indirect Evidence: $k_{AB} = k_{AC} = 6, pi_A = 0.1$"), color = TeX("True: $OR_{BC}$"), x = "", y = "power_het_eqcor") 
,
df_indirect_new %>% filter(k_ab == 12, pi_a == 0.1) %>% 
  ggplot(aes(x = k_ac, y = power_het_eqcor, color = factor(OR_bc)))  + 
  geom_hline(size = 1.2, aes(yintercept = power_het_eqcor, color = factor(OR_bc))) +
  facet_wrap(~tau) + labs(title = TeX("Indirect Evidence: $k_{AB} = k_{AC} = 12, pi_A = 0.1$"), color = TeX("True: $OR_{BC}$"), x = "", y = "power_het_eqcor") 

,

df_indirect_new %>% filter(k_ab == 6, pi_a == 0.5) %>% 
  ggplot(aes(x = k_ac, y = power_het_eqcor, color = factor(OR_bc)))  + geom_hline(size = 1.2, aes(yintercept = power_het_eqcor, color = factor(OR_bc))) +
  facet_wrap(~tau) + labs(title = TeX("Indirect Evidence: $k_{AB} = k_{AC} = 6, pi_A = 0.5$"), color = TeX("True: $OR_{BC}$"), x = "", y = "power_het_eqcor")  
,
df_indirect_new %>% filter(k_ab == 12, pi_a == 0.5) %>% 
  ggplot(aes(x = k_ac, y = power_het_eqcor, color = factor(OR_bc)))  + geom_hline(size = 1.2, aes(yintercept = power_het_eqcor, color = factor(OR_bc))) +
  facet_wrap(~tau) + labs(title = TeX("Indirect Evidence: $k_{AB} = k_{AC} = 12, pi_A = 0.5$"), color = TeX("True: $OR_{BC}$"), x = "", y = "power_het_eqcor") 
)

```


```{r, fig.height=5.5, fig.width=12}
### power_het_eqcor 

gridExtra::grid.arrange(

df_direct_new %>% filter(k_bc %in% c(1,2,3,6), pi_a == 0.1) %>% 
  ggplot(aes(x = k_bc, y = power_het_eqcor, color = factor(OR_bc)))  + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Direct Evi: k_bc in c(1,2,3,6), pi_a = 0.1", color = "True OR_bc") + theme_bw() + scale_x_continuous(breaks = seq(1, 6, 1), labels = as.character(seq(1, 6, 1)))

,
df_direct_new %>% filter(k_bc %in% c(2,4,6,12), pi_a == 0.1) %>% 
  ggplot(aes(x = k_bc, y = power_het_eqcor, color = factor(OR_bc)))  + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Direct Evi: k_bc in c(2,4,6,12), pi_a = 0.1", color = "True OR_bc") + theme_bw() + scale_x_continuous(breaks = seq(2, 12, 2), labels = as.character(seq(2, 12, 2)))

,

df_direct_new %>% filter(k_bc %in% c(1,2,3,6), pi_a == 0.5) %>% 
  ggplot(aes(x = k_bc, y = power_het_eqcor, color = factor(OR_bc)))  + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Direct Evi: k_bc in c(1,2,3,6), pi_a = 0.5", color = "True OR_bc") + theme_bw() + scale_x_continuous(breaks = seq(1, 6, 1), labels = as.character(seq(1, 6, 1)))

,
df_direct_new %>% filter(k_bc %in% c(2,4,6,12), pi_a == 0.5) %>% 
  ggplot(aes(x = k_bc, y = power_het_eqcor, color = factor(OR_bc)))  + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = "Direct Evi:  k_bc in c(2,4,6,12), pi_a = 0.5", color = "True OR_bc") + theme_bw() + scale_x_continuous(breaks = seq(2, 12, 2), labels = as.character(seq(2, 12, 2)))
)

```


```{r, fig.height=5.5, fig.width=12}
# Compare direct and indirect evidence power_het_eqcors

gridExtra::grid.arrange(

df_direct_new %>% filter(k_bc %in% c(1,2,3,6), pi_a == 0.1) %>% 
  ggplot(aes(x = k_bc, y = power_het_eqcor, color = factor(OR_bc)))  + geom_line(size = 1.2) + facet_wrap(~tau) +   
  labs(title = TeX("Direct ($k_{BC}$) vs. Indirect ($k_{AB} = k_{AC} = 6$) Evidence, $pi_a = 0.1$"), x = TeX("$k_{BC}$"), color = TeX("True $OR_{BC}$"), y = "power_het_eqcor") + geom_hline(linetype = "dashed", data = df_indirect_new %>% filter(k_ab == 6, pi_a == 0.1), aes(yintercept = power_het_eqcor, color = factor(OR_bc))) + scale_x_continuous(breaks = seq(1, 6, 1), labels = as.character(seq(1, 6, 1)))
,
df_direct_new %>% filter(k_bc %in% c(2,4,6,12), pi_a == 0.1) %>% 
  ggplot(aes(x = k_bc, y = power_het_eqcor, color = factor(OR_bc)))  + geom_line(size = 1.2) + facet_wrap(~tau) +  
  labs(title = TeX("Direct ($k_{BC}$) vs. Indirect ($k_{AB} = k_{AC} = 6$) Evidence, $pi_a = 0.1$"), x = TeX("$k_{BC}$"), color = TeX("True $OR_{BC}$"), y = "power_het_eqcor") + geom_hline(linetype = "dashed", data = df_indirect_new %>% filter(k_ab == 12, pi_a == 0.1), aes(yintercept = power_het_eqcor, color = factor(OR_bc))) + scale_x_continuous(breaks = seq(2, 12, 2), labels = as.character(seq(2, 12, 2)))

,

df_direct_new %>% filter(k_bc %in% c(1,2,3,6), pi_a == 0.5) %>% 
  ggplot(aes(x = k_bc, y = power_het_eqcor, color = factor(OR_bc)))  + geom_line(size = 1.2) + facet_wrap(~tau) + 
    labs(title = TeX("Direct ($k_{BC}$) vs. Indirect ($k_{AB} = k_{AC} = 6$) Evidence, $pi_a = 0.5$"), x = TeX("$k_{BC}$"), color = TeX("True $OR_{BC}$"), y = "power_het_eqcor") + geom_hline(linetype = "dashed", data = df_indirect_new %>% filter(k_ab == 6, pi_a == 0.5), aes(yintercept = power_het_eqcor, color = factor(OR_bc))) + scale_x_continuous(breaks = seq(1, 6, 1), labels = as.character(seq(1, 6, 1)))
,
df_direct_new %>% filter(k_bc %in% c(2,4,6,12), pi_a == 0.5) %>% 
  ggplot(aes(x = k_bc, y = power_het_eqcor, color = factor(OR_bc)))  + geom_line(size = 1.2) + facet_wrap(~tau) + 
  labs(title = TeX("Direct ($k_{BC}$) vs. Indirect ($k_{AB} = k_{AC} = 12$) Evidence, $pi_a = 0.5$"), x = TeX("$k_{BC}$"), color = TeX("True $OR_{BC}$"), y = "power_het_eqcor") + geom_hline(linetype = "dashed", data = df_indirect_new %>% filter(k_ab == 12, pi_a == 0.5), aes(yintercept = power_het_eqcor, color = factor(OR_bc))) + scale_x_continuous(breaks = seq(2, 12, 2), labels = as.character(seq(2, 12, 2)))
)
```




```{r, fig.height=5.5, fig.width=12}
load("df_indirect_BNMA_AB_bias3.RData")
load("df_direct_BNMA_AB_bias3.RData")
load("df_overall_BNMA_AB_bias3.RData")

df_indirect_new = df_indirect_new[which(df_indirect_new$pi_a==0.5),]
df_direct_new = df_direct_new[which(df_direct_new$pi_a==0.5),]

a <- df_BNMA_new %>% filter(k_ab == 6) %>% 
  ggplot(aes(x = k_bc, y = power_het_eqcor, color = factor(OR_bc))) + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = TeX("Overall vs. Only Indirect Evidence ($k_{AB}$ = $k_{AC}$ = 6)"), color = TeX("True $OR_{BC}$"), y = "power_het_eqcor", x = "Number of Studies") + geom_hline(linetype = "dashed", data = df_indirect_new[which(df_indirect_new$k_ab==6),], aes(yintercept = power_het_eqcor, color = factor(OR_bc))) + scale_x_continuous(breaks = seq(1, 6, 1), labels = as.character(seq(1, 6, 1)))
  

b <- df_BNMA_new %>% filter(k_ab == 12) %>% 
  ggplot(aes(x = k_bc, y = power_het_eqcor, color = factor(OR_bc))) + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = TeX("Overall vs. Only Indirect Evidence ($k_{AB}$ = $k_{AC}$ = 12)"), color = TeX("True $OR_{BC}$"), y = "power_het_eqcor", x = "Number of Studies") + geom_hline(linetype = "dashed", data = df_indirect_new[which(df_indirect_new$k_ab==12),], aes(yintercept = power_het_eqcor, color = factor(OR_bc))) + scale_x_continuous(breaks = seq(2, 12, 2), labels = as.character(seq(2, 12, 2)))


c <- df_BNMA_new %>% filter(k_ab == 6) %>% 
  ggplot(aes(x = k_bc, y = power_het_eqcor, color = factor(OR_bc))) + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = TeX("Overall vs. Only Direct Evidence ($k_{BC}$ = 1, 2, 3, 6)"), color = TeX("True $OR_{BC}$"),  y = "power_het_eqcor", x = "Number of Studies") + geom_line(linetype = "dotdash", data = df_direct_new[which(df_direct_new$k_bc %in% c(1,2,3,6)),], aes(y = power_het_eqcor, x = k_bc, color = factor(OR_bc)))+ scale_x_continuous(breaks = seq(1, 6, 1), labels = as.character(seq(1, 6, 1)))
  

d <- df_BNMA_new %>% filter(k_ab == 12) %>% 
  ggplot(aes(x = k_bc, y = power_het_eqcor, color = factor(OR_bc))) + geom_line(size = 1.2) +
  facet_wrap(~tau) + labs(title = TeX("Overall vs. Only Direct Evidence ($k_{BC}$ = 2, 4, 6, 12)"), color = TeX("True $OR_{BC}$"), y = "power_het_eqcor", x = "Number of Studies") + geom_line(linetype = "dotdash", data = df_direct_new[which(df_direct_new$k_bc %in% c(2,4,6,12)),], aes(y = power_het_eqcor, x = k_bc, color = factor(OR_bc)))+ scale_x_continuous(breaks = seq(2, 12, 2), labels = as.character(seq(2, 12, 2)))

gridExtra::grid.arrange(a,b,c,d,ncol = 2)
```






