---
title: "Continuous_result"
author: "Yicheng Shen"
date: "2023-06-13"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(gemtc)
```

```{r}
data(parkinson)
parkinson_rn = parkinson
colnames(parkinson_rn) = c("study", "treatment", "mean", "std.dev", "sampleSize", 
                           "treatment", "mean", "std.dev", "sampleSize",
                           "treatment", "mean", "std.dev", "sampleSize")

parkinson_ab <- data.frame(matrix(ncol = 5, nrow = 0))
colnames(parkinson_ab) <- c("study", "treatment", "mean", "std.dev", "sampleSize")

for (i in 1:7) {
  if (!is.na(parkinson_rn[i,10])){
    treatment = as.character(parkinson_rn[i,c(2,6,10)])
    event_n = rbind(parkinson_rn[i,3:5],parkinson_rn[i,7:9],parkinson_rn[i,11:13])
    study = rep(i, length(treatment))
    parkinson_ab = rbind(parkinson_ab, cbind(study, treatment, event_n))
  } else{ 
    treatment = as.character(parkinson_rn[i,c(2,6)])
    event_n = rbind(parkinson_rn[i,3:5],parkinson_rn[i,7:9])
    study = rep(i, length(treatment))
    parkinson_ab = rbind(parkinson_ab, cbind(study, treatment, event_n))
  }
}
# save(parkinson_ab, file = "parkinson_ab.RData")
# load("parkinson_ab.RData")
```

```{r}
parkinson_net <- mtc.network(parkinson_ab)
plot(parkinson_net)
```

```{r}
parkinson_eff = data.frame(sid = as.numeric(parkinson_ab$study), tid = as.numeric(parkinson_ab$treatment), 
                           r = as.numeric(parkinson_ab$mean), n = as.numeric(parkinson_ab$sampleSize))

library("igraph")
source("functions.R")

dir.binary(parkinson_eff)
eff.binary(parkinson_eff)
```



```{r}
cons.model <- mtc.model(parkinson_net, type="consistency", 
                        likelihood="normal", link="identity", linearModel="random")
cons.out <- mtc.run(cons.model, n.adapt=20000, n.iter=50000, thin=1)
summary(cons.out)
```


```{r}

```

