---
title: "Coronary Result"
author: "Yicheng Shen"
date: "2023-04-12"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = T, warning = F)
library(tidyverse)
library(kableExtra)
ggplot2::theme_set(ggplot2::theme_bw())
knitr::opts_chunk$set(out.width = "100%", fig.align = 'center')
```


```{r}
load("result_rate_bleeding.RData")
load("order_MACE.RData")
load("result_rate_MACE.RData")
```


```{r, eval = F}
Bleed_data %>% filter(treatment %in% c("A", "B")) %>% summarize(sum(sampleSize))
Bleed_data %>% filter(treatment %in% c("A", "B")) %>% summarize(n_distinct(study))

Bleed_data %>% filter(treatment %in% c("A", "C")) %>% summarize(sum(sampleSize))
Bleed_data %>% filter(treatment %in% c("A", "C")) %>% summarize(n_distinct(study))

Bleed_data %>% filter(treatment %in% c("A", "D")) %>% summarize(sum(sampleSize))
Bleed_data %>% filter(treatment %in% c("A", "D")) %>% summarize(n_distinct(study))

Bleed_data %>% filter(treatment %in% c("B", "C")) %>% summarize(sum(sampleSize))
Bleed_data %>% filter(treatment %in% c("B", "C")) %>% summarize(n_distinct(study))

Bleed_data %>% filter(treatment %in% c("B", "D")) %>% summarize(sum(sampleSize))
Bleed_data %>% filter(treatment %in% c("B", "D")) %>% summarize(n_distinct(study))

Bleed_data %>% filter(treatment %in% c("C", "D")) %>% summarize(sum(sampleSize))
Bleed_data %>% filter(treatment %in% c("C", "D")) %>% summarize(n_distinct(study))
```


```{r}
load("result_rate_bleeding.RData")
colnames(result_rate_bleeding) <- c("Power AB","Power AC","Power AD",
                                    "Power BC","Power BD","Power CD",
                                    "Rank A last")
result_rate_bleeding %>% data.frame()
```


```{r}
load("result_rate_bleeding.RData")
result_rate_bleeding_all = result_rate_bleeding %>% data.frame()
load("result_rate_bleeding_AB.RData")
result_rate_bleeding_all = rbind(result_rate_bleeding_all, 
                                 result_rate_bleeding %>% data.frame())
load("result_rate_bleeding_AC.RData")
result_rate_bleeding_all = rbind(result_rate_bleeding_all, 
                                 result_rate_bleeding %>% data.frame())
load("result_rate_bleeding_AD.RData")
result_rate_bleeding_all = rbind(result_rate_bleeding_all, 
                                 result_rate_bleeding %>% data.frame())

result_rate_bleeding_all = cbind(c("Original", "Add one AB study", "Add one AC study", "Add one AD study"), result_rate_bleeding_all)

colnames(result_rate_bleeding_all) <- c("Modification",
                                    "Power AB","Power AC","Power AD",
                                    "Power BC","Power BD","Power CD",
                                    "Rank A last")
result_rate_bleeding_all


result_rate_bleeding_all %>% 
  mutate(Modification = factor(Modification, 
                               levels = c("Original", 
                                          "Add one AB study", "Add one AC study", "Add one AD study"))) %>% 
  pivot_longer(cols = 2:7, names_to = "Comparison", values_to = "Power") %>% 
  ggplot() + geom_col(aes(x = Comparison, y = Power, fill = Modification), position = position_dodge(0.8), width = 0.75)  + labs(x=" ")
```


```{r}
load("result_rate_bleeding.RData")
result_rate_bleeding_all = result_rate_bleeding %>% data.frame()
load("result_rate_bleeding_AB.RData")
result_rate_bleeding_all = rbind(result_rate_bleeding_all, 
                                 result_rate_bleeding %>% data.frame())
load("result_rate_bleeding_AC.RData")
result_rate_bleeding_all = rbind(result_rate_bleeding_all, 
                                 result_rate_bleeding %>% data.frame())
load("result_rate_bleeding_AD.RData")
result_rate_bleeding_all = rbind(result_rate_bleeding_all, 
                                 result_rate_bleeding %>% data.frame())
load("result_rate_bleeding_CD.RData")
result_rate_bleeding_all = rbind(result_rate_bleeding_all, 
                                 result_rate_bleeding %>% data.frame())

result_rate_bleeding_all = cbind(c("Original", "Add one AB study", "Add one AC study", "Add one AD study", "Add one CD study"), result_rate_bleeding_all)

colnames(result_rate_bleeding_all) <- c("Modification",
                                    "Power AB","Power AC","Power AD",
                                    "Power BC","Power BD","Power CD",
                                    "Rank A last")
result_rate_bleeding_all


result_rate_bleeding_all %>% 
  mutate(Modification = factor(Modification, 
                               levels = c("Original", 
                                          "Add one AB study", "Add one AC study", "Add one AD study", "Add one CD study"))) %>% 
  pivot_longer(cols = 2:7, names_to = "Comparison", values_to = "Power") %>% 
  ggplot() + geom_col(aes(x = Comparison, y = Power, fill = Modification), position = position_dodge(0.8), width = 0.75)  + labs(x=" ")
```
```{r}
load("result_rate_bleeding.RData")
result_rate_bleeding_all = result_rate_bleeding %>% data.frame()
load("result_rate_bleeding_AB.RData")
result_rate_bleeding_all = rbind(result_rate_bleeding_all, 
                                 result_rate_bleeding %>% data.frame())
load("result_rate_bleeding_AC.RData")
result_rate_bleeding_all = rbind(result_rate_bleeding_all, 
                                 result_rate_bleeding %>% data.frame())
load("result_rate_bleeding_AD.RData")
result_rate_bleeding_all = rbind(result_rate_bleeding_all, 
                                 result_rate_bleeding %>% data.frame())
load("result_rate_bleeding_BC.RData")
result_rate_bleeding_all = rbind(result_rate_bleeding_all, 
                                 result_rate_bleeding %>% data.frame())
load("result_rate_bleeding_BD.RData")
result_rate_bleeding_all = rbind(result_rate_bleeding_all, 
                                 result_rate_bleeding %>% data.frame())
load("result_rate_bleeding_CD.RData")
result_rate_bleeding_all = rbind(result_rate_bleeding_all, 
                                 result_rate_bleeding %>% data.frame())

result_rate_bleeding_all = cbind(c("Original", "Add one AB study", "Add one AC study", "Add one AD study", "Add one BC study","Add one BD study", "Add one CD study"), result_rate_bleeding_all)

colnames(result_rate_bleeding_all) <- c("Modification",
                                    "Power AB","Power AC","Power AD",
                                    "Power BC","Power BD","Power CD",
                                    "Rank A last")
result_rate_bleeding_all


result_rate_bleeding_all %>% 
  mutate(Modification = factor(Modification, 
                               levels = c("Original", "Add one AB study", "Add one AC study", "Add one AD study", 
                                          "Add one BC study","Add one BD study", "Add one CD study"))) %>% 
  pivot_longer(cols = 2:7, names_to = "Comparison", values_to = "Power") %>% 
  ggplot() + geom_col(aes(x = Comparison, y = Power, fill = Modification), position = position_dodge(0.8), width = 0.75)  + labs(x=" ")
```




```{r}
library("igraph")
source("functions.R")

bleed <- read.table("Data_Bleeding.csv", sep=",", header=TRUE)

######## Row 7 and 8 need to be combined
bleed[7,3:7] = bleed[7,3:7] + bleed[8,3:7]
bleed <- bleed[-8,]

Bleed_data <- bleed[,c("study", "treatment", "n", "TIMImajor")]
Bleed_data = Bleed_data[1:(nrow(Bleed_data)-2), ]

trt <- c("A","B", "C","D")
# trt <- c("VKA + DAPT", "VKA + P2Y12", "NOAC + DAPT", "NOAC + P2Y12")

trts <- read.table(textConnection('id description
                                  A "VKA + DAPT"
                                  B "VKA + P2Y12"
                                  C "NOAC + DAPT"
                                  D "NOAC + P2Y12"'), header=TRUE)

colnames(Bleed_data) = c("study","treatment", "sampleSize","responders")

Bleed_data_eff = data.frame(sid = Bleed_data$study, tid = Bleed_data$treatment, r = Bleed_data$responders, n = Bleed_data$sampleSize)

eff.binary(Bleed_data_eff)

effective = eff.binary(Bleed_data_eff)

effective1 = effective$eff.studies

colnames(effective1) = c("A","B", "C","D")
rownames(effective1) = c("A","B", "C","D")

effective2 = effective$eff.sz

colnames(effective1) = c("A","B", "C","D")
rownames(effective1) = c("A","B", "C","D")

effective3 = effective$eff.prec

colnames(effective1) = c("A","B", "C","D")
rownames(effective1) = c("A","B", "C","D")

stargazer::stargazer(effective3)

stargazer::stargazer(eff.binary(Bleed_data_eff))
```










```{r}
sort(prop.table(table(order_MACE)), decreasing = T) 
```


```{r}
# prop.table(table(order_MACE)) 
sort(prop.table(table(order_MACE)), decreasing = T) 

hist(table(order_MACE), breaks = 15)
abline(v=1/16*10000, lwd = 6)
```

```{r}
MACE_data %>% filter(treatment %in% c("A", "B")) %>% summarize(sum(sampleSize))
MACE_data %>% filter(treatment %in% c("A", "B")) %>% summarize(n_distinct(study))

MACE_data %>% filter(treatment %in% c("A", "C")) %>% summarize(sum(sampleSize))
MACE_data %>% filter(treatment %in% c("A", "C")) %>% summarize(n_distinct(study))

MACE_data %>% filter(treatment %in% c("A", "D")) %>% summarize(sum(sampleSize))
MACE_data %>% filter(treatment %in% c("A", "D")) %>% summarize(n_distinct(study))

MACE_data %>% filter(treatment %in% c("B", "C")) %>% summarize(sum(sampleSize))
MACE_data %>% filter(treatment %in% c("B", "C")) %>% summarize(n_distinct(study))

MACE_data %>% filter(treatment %in% c("B", "D")) %>% summarize(sum(sampleSize))
MACE_data %>% filter(treatment %in% c("B", "D")) %>% summarize(n_distinct(study))

MACE_data %>% filter(treatment %in% c("C", "D")) %>% summarize(sum(sampleSize))
MACE_data %>% filter(treatment %in% c("C", "D")) %>% summarize(n_distinct(study))
```



```{r}
load("result_rate_MACE.RData")
result_rate_MACE_all = result_rate_MACE %>% data.frame() %>% data.frame()
load("result_rate_MACE_AB.RData")
result_rate_MACE_all = rbind(result_rate_MACE_all, 
                                 result_rate_MACE %>% data.frame())
load("result_rate_MACE_AC.RData")
result_rate_MACE_all = rbind(result_rate_MACE_all, 
                                 result_rate_MACE %>% data.frame())
load("result_rate_MACE_AD.RData")
result_rate_MACE_all = rbind(result_rate_MACE_all, 
                                 result_rate_MACE %>% data.frame())

result_rate_MACE_all = cbind(c("Original", "Add AB", "Add AC", "Add AD"), result_rate_MACE_all)

colnames(result_rate_MACE_all) <- c("Modification",
                                    "Power AB","Power AC","Power AD",
                                    "Power BC","Power BD","Power CD")
result_rate_MACE_all

result_rate_MACE_all %>% 
  mutate(Modification = factor(Modification, levels = c("Original", "Add AB", "Add AC", "Add AD"))) %>% 
  pivot_longer(cols = 2:7, names_to = "Comparison", values_to = "Power") %>% 
  ggplot() + geom_col(aes(x = Comparison, y = Power, fill = Modification), position = position_dodge(0.8), width = 0.7) 
```

```{r, fig.height=6, fig.width=12.5}
# library(foreach)
# library(doParallel)
# # Initialize parallel backend
# cl <- makeCluster(12)
# 
# # Register the parallel backend
# registerDoParallel(cl)



library(tidyverse)
# library(gemtc)


set.seed(2023)

######## Import data
bleed <- read.table("Data_Bleeding.csv", sep=",", header=TRUE)
mace <- read.table("Data_MACE.csv", sep=",", header=TRUE)


######## Row 7 and 8 need to be combined
bleed[7,3:7] = bleed[7,3:7] + bleed[8,3:7]
bleed <- bleed[-8,]
mace[7,3:10] = mace[7,3:10] + mace[8,3:10]
mace <- mace[-8,]


Bleed_data <- bleed[,c("study", "treatment", "n", "TIMImajor")]
Bleed_data = Bleed_data[1:(nrow(Bleed_data)-2), ]

MACE_data <- mace[,c("study", "treatment", "n", "MACE")]        
MACE_data = MACE_data[1:(nrow(MACE_data)-2), ]




library(pcnetmeta)
nma.networkplot(study, treatment, data = Bleed_data, title = "Coronary Antithrombotic Treatment Regimens", 
                trtname = c("A: VKA + DAPT", "B: VKA + P2Y12", "C: NOAC + DAPT", "D: NOAC + P2Y12"),
                node.col = "orange", 
                edge.col = "gray", adjust.thick = 8, text.cex = 1.3)

nma.networkplot(study, treatment, data = Bleed_data, title = "Coronary Major Bleeding", 
                node.col = "orange", 
                edge.col = "gray", adjust.thick = 8)
```
